# Generated by Django 4.1.7 on 2024-04-25 19:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('address', models.CharField(choices=[('Mekelle', 'Mekelle'), ('Addis Ababa', 'Addis Ababa'), ('Adigrat', 'Adigrat')], max_length=50)),
                ('profile_picture', models.ImageField(upload_to='profile_pics/')),
                ('phone_number', models.CharField(max_length=15)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_product', models.CharField(choices=[('house', 'House'), ('car', 'Car'), ('bicycle', 'Bicycle'), ('motor', 'Motor')], max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image1', models.ImageField(upload_to='rent_images/')),
                ('image2', models.ImageField(upload_to='rent_images/')),
                ('price_type', models.CharField(choices=[('day', 'Per Day'), ('hour', 'Per Hour'), ('week', 'Per Week'), ('year', 'Per Year')], max_length=10)),
                ('ordering_phone_number', models.CharField(max_length=15)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image1', models.ImageField(upload_to='product_images/')),
                ('image2', models.ImageField(upload_to='product_images/')),
                ('price_type', models.CharField(choices=[('piece', 'Per Piece'), ('jmla', 'Per Jmla'), ('packet', 'Per Packet')], max_length=10)),
                ('ordering_phone_number', models.CharField(max_length=15)),
                ('likes', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
