# Generated by Django 4.1.7 on 2024-05-04 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_like'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
